Learning Numpy In Detailed

In [1]:
import numpy as np

list1 = [1,2,3,4,5,6]
print(type(list1))

<class 'list'>


In [2]:
arr_list = np.array(list1)
print(arr_list)

[1 2 3 4 5 6]


In [3]:
print(arr_list.ndim)

1


.ndim is used check how many dimensional array is this

2. Two Dimensional Array Creation
   

In [4]:
list1 = [1,2,3]
list2 = [3,4,5]

arr_list2 = np.array([list1,list2])
print(arr_list2)

[[1 2 3]
 [3 4 5]]


In [7]:
print(f"It is {(arr_list2.ndim)} dimensional array")

It is 2 dimensional array


3. Three Dimensional Array
   

In [8]:
list1 = [1,2,3]
list2 = [3,4,5]
list3 = [6,7,8]

arr_list3 = np.array([[list1, list2, list3]])
print(arr_list3)


[[[1 2 3]
  [3 4 5]
  [6 7 8]]]


In [9]:
print(f"It is {(arr_list3.ndim)} dimensional array")

It is 3 dimensional array
