# Learning Numpy In Detailed

NumPy is a core Python library for numerical computing, built for handling large arrays and matrices efficiently. It is significantly faster than Python's built-in lists because it uses optimized C language style storage where actual values are stored at contiguous locations (not object reference).


In [1]:
import numpy as np

list1 = [1,2,3,4,5,6]
print(type(list1))

<class 'list'>


In [2]:
arr_list = np.array(list1)
print(arr_list)

[1 2 3 4 5 6]


In [3]:
print(arr_list.ndim)

1


.ndim is used check how many dimensional array is this

# 2. Two Dimensional Array Creation
   

In [4]:
list1 = [1,2,3]
list2 = [3,4,5]

arr_list2 = np.array([list1,list2])
print(arr_list2)

[[1 2 3]
 [3 4 5]]


In [7]:
print(f"It is {(arr_list2.ndim)} dimensional array")

It is 2 dimensional array


3. Three Dimensional Array
   

In [8]:
list1 = [1,2,3]
list2 = [3,4,5]
list3 = [6,7,8]

arr_list3 = np.array([[list1, list2, list3]])
print(arr_list3)


[[[1 2 3]
  [3 4 5]
  [6 7 8]]]


In [9]:
print(f"It is {(arr_list3.ndim)} dimensional array")

It is 3 dimensional array


# 2. Numpy Array Attributes

In [1]:
import numpy as np

arr1 = np.array([[[1.1,2.2,3.1], [4.1,5.1,6.1], [7.1,7.4,7.8]]])
print(type(arr1))


<class 'numpy.ndarray'>


In [11]:
print(f"Shape {arr1.shape}")
print(arr1)
print(f"It is {arr1.ndim} dimensional array")
print(f"size {arr1.size}")

Shape (1, 3, 3)
[[[1.1 2.2 3.1]
  [4.1 5.1 6.1]
  [7.1 7.4 7.8]]]
It is 3 dimensional array
size 9


# 3. Array Initialization Method

In [12]:
# Identity Mattricx

id_arr = np.eye(3)
print(id_arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [14]:
# Empty array
em_arr = np.empty((2))
print(em_arr)

[0.00000000e+000 1.19828262e-311]


In [2]:
# evenly spaced array
ev_arr = np.arange(1,10,2)
print(ev_arr)

# arrange(start, less than- end, spacing)

[1 3 5 7 9]


In [24]:
# Specific number of equally (spaced) values between a range

print(np.linspace(1,10,10))

#linspace(start,end, divide in how many numbers

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [5]:
# Random value array- float

print(np.random.rand(3,2))

[[0.6764017  0.33155729]
 [0.98875779 0.86070661]
 [0.48377635 0.43158716]]


In [29]:
# Random value array- int

print(np.random.randint(1,10, (4,3)))

# random.randint(between 1, 10, (shape))

[[2 5 8]
 [9 8 4]
 [8 7 7]
 [2 1 6]]


# 4. Array Indexing and Slicing

1. Array indexing is the same as accessing an array element.
2. You can access an array element by referring to its index number.
3. The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.

In [43]:
arr_in = np.array([1,2,3,4,5,6])
print(arr_in)

#Sum of array indexing
sum_in = arr_in[0] + arr_in[1]
print(sum_in)

[1 2 3 4 5 6]
3


4.1 Array Indexing 

4.2 Array Slicing

Slicing in python means taking elements from one given index to another given index.

We pass slice instead of index like this: [start:end].

We can also define the step, like this: [start:end:step].

If we don't pass start its considered 0

If we don't pass end its considered length of array in that dimension

If we don't pass step its considered 1

In [46]:
arr_sl = np.array([1,2,3,4,5,6])
print(arr_sl)

print(arr_sl[1::2])

# (Start: end: step)

[1 2 3 4 5 6]
[2 4 6]


In [1]:
import numpy as np
arr_sl = np.array([1,2,3,4,5,6])
print(arr_sl)


[1 2 3 4 5 6]
